config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :issues, only: [:new, :create, :show]
end

app/models/device.rb
class Device
  include Mongoid::Document

  has_many :issues

  field :name
  field :released_on, type: Date
  field :scapegoats, type: Array

  validates :name, presence: true
  validates :released_on, presence: true
  validates :scapegoats, presence: true

  def to_s
    name
  end

  def obsolete_on
    released_on + 18.months
  end
end

app/models/issue.rb
class Issue
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Token

  SCAPEGOATS = ['Qualcomm', 'LGE', 'Motorola', 'Asus', 'Verizon', 'Samsung', 'HTC', 'Corning', 'ARM']

  belongs_to :device

  token

  field :device
  field :description

  field :stars, type: Integer
  field :closed_on, type: Date
  field :closed_by
  field :reason

  validates :device, presence: true
  validates :description, presence: true, length: { maximum: 500 }

  before_save do
    self.stars = rand(100..2000)
    self.closed_by = "#{('a'..'z').to_a.shuffle.first(2).join}...@google.com"
    self.closed_on = rand(1.year.from_now..3.years.from_now)
    self.reason = give_me_a_reason
  end

  def obsolete?
    device.obsolete_on < closed_on
  end

  def to_s
    token
  end

  private
  def give_me_a_reason
    # TODO: fix this. Provide "status" column
    if obsolete?
      '(No comment was entered for this change.)'
    elsif rand(11) <= 8
      "looks like internal issue http://b/#{rand(10000000..99999999)} which seems to be blocked on #{device.scapegoats.sample}?"
    else
      'contact customer support.'
    end
  end
end

app/models/permitted_params.rb
class PermittedParams < Struct.new(:params)
  def issue
    params.require(:issue).permit(*issue_attributes)
  end

  def issue_attributes
    [:device, :description]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :permitted_params

  protected
  def permitted_params
    @permitted_params ||= PermittedParams.new(params)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show]

  def new
    @devices = Device.order(release_date: :desc)
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(permitted_params.issue)
    if @issue.save
      flash[:success] = t('flash.issue.success.create')
      redirect_to issue_path(@issue)
    else
      flash.now[:error] = t('flash.issue.error.create')
      render :new
    end
  end

  protected
  def set_issue
    @issue = Issue.find_by_token params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end
end

app/views/issues/_form.html.slim
.container
  = form_for @issue do |f|
    - if f.object.errors.full_messages.any?
      .alert.alert-danger.fade.in
        h4= t('helpers.form.error')
        - for msg in f.object.errors.full_messages
          = msg
          br

    .form-group
      = f.label :device, Device.model_name.human
      = f.select :device, @devices.map { |d| [d.name, d.id] }, { }, class: 'form-control', required: true
    .form-group
      = f.label :description, Issue.human_attribute_name(:description)
      = f.text_area :description, class: 'form-control', rows: 8, required: true, max: 500
      p.help-block= t('.description_help')
    .form-group
      = f.submit t('.submit'), class: 'btn btn-primary pull-right btn-block btn-lg', disable_with: t('helpers.please_wait'), remote: true

app/views/issues/new.html.slim
- title t('.title')
.featurette.featurette-indigo
  .container
    h1= yield :title
.featurette
  == render 'form'

app/views/issues/show.html.slim
- title t('.title', issue: @issue)
.featurette.featurette-indigo
  .container
    h1= yield :title
.featurette
  .container
    h2= t('.details')
    p
      b> #{Issue.human_attribute_name(:stars)}:
      = @issue.stars
    p
      b> #{Device.model_name.human}:
      = @issue.device.name
    p
      b= Issue.human_attribute_name(:description)
      p= simple_format(@issue.description)
    hr
    h2= t('.solution_found')
    blockquote
      p
        b> #{Issue.human_attribute_name(:closed_by)}:
        = @issue.closed_by
      p
        b> #{Issue.human_attribute_name(:closed_on)}:
        = l(@issue.closed_on, format: :long)
      - if @issue.obsolete?
        p
          span.label.label-default= t('.obsolete_html')
        p
          em.text-muted= @issue.reason
      - elsif @issue.reason == 'contact customer support.'
        p.lead
          span.label.label-default= t('.wrong_forum_html')
        p= simple_format(@issue.reason)
      - else
        p.lead
          span.label.label-warning= t('.restricted_html')
        p= simple_format(@issue.reason)
    hr
    = link_to t('.submit_new_issue'), new_issue_path, class: 'btn btn-default btn-sm btn-block'

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale.to_s
  head
    meta charset='utf-8'
    meta content='IE=edge' http-equiv='X-UA-Compatible'
    meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0'
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags

    title= yield_or_default :title, action_name.titlecase
    = csrf_meta_tags
    = yield :head

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    /! Favicons
    link href=asset_path('apple-touch-icon-precomposed.png') rel='apple-touch-icon-precomposed' sizes='152x152'
    link href=asset_path('apple-touch-icon-precomposed.png') rel='icon'

    /! Turbolinks require javascript tags inside the head
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/webfont/1.5.6/webfont.js', 'application', 'data-turbolinks-track': 'reload'
    = analytics_init if Rails.env.production? && GA.tracker.present?

    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js', 'respond.js'

  body
    = yield
    == render 'shared/footer'

app/views/shared/_footer.html.slim
footer
  .container
    ' © 2017
    = link_to 'Android™ Bug Solver', root_path
    '
    = link_to 'https://github.com/tagliala/android-bug-solver' do
      span.mdi.mdi-github-circle
    p
      small
        | Android is a trademark of Google Inc.
        br
        | This application is neither designed nor endorsed by Google Inc. Any resemblance to their way of handling issues for aging handsets is purely coincidental.

app/views/welcome/index.html.slim
- title t('.title')

- content_for :head do
  meta name='description' content=t('.description')

.featurette.featurette-indigo
  .container
    h1.slabme
      span.slabtext> Android Bug Solver
      span.slabtext> Solves any android bug within seconds!
      span.slabtext> 100% Guaranteed
      span.slabtext> Give a try!
    = link_to t('.submit_your_issue'), new_issue_path, class: 'btn btn-block btn-center btn-lg btn-primary'
.featurette.featurette-amber
  .container
    h2.slabme How it works?
    p.lead
      | <b>Android Bug Solver</b> uses a <b>Time Machine</b> to time travel in the future and find a solution. Then it will submit a Pull Request to the AOSP repository.